### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tan-matt** [FAST-HEP/fast-curator#33]
Running Fast Curator version 0.4.1 on a local cluster, using XrootD files

**Comment by benkrikler** [comment]
Thanks @tan-matt can you add the traceback you see when you get this crash?

**Comment by tan-matt** [comment]
`fast_curator -d Background --mc -t Scatters -o dataset_cfgs/mdc3_commissioning-scatters.yml root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/lz/lz/data/MDC3tests/x86_64-centos7-gcc7-opt/lz_mdc3_commissioning/LZAP-4.3.1/20180222/4.9.6_8.5.6/*.root
Traceback (most recent call last):
  File "/home/tanm/miniconda3/envs/fast_lz/bin/fast_curator", line 10, in <module>
    sys.exit(main_write())
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/__main__.py", line 62, in main_write
    tree_name=args.tree_name)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/write.py", line 27, in prepare_file_list
    full_list = expand_files.expand_file_list(files, prefix=prefix)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/catalogues/__init__.py", line 15, in expand_file_list
    return expand_file_list_generic(files, prefix, glob=glob)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/catalogues/__init__.py", line 46, in expand_file_list_generic
    expanded = glob(name)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/xrootd_glob.py", line 35, in glob
    return xrootd_glob(pathname)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/xrootd_glob.py", line 57, in xrootd_glob
    for entry in dirlist["dirlist"]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by tan-matt** [comment]
Traceback (most recent call last):
  File "/home/tanm/miniconda3/envs/fast_lz/bin/fast_curator", line 10, in <module>
    sys.exit(main_write())
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/__main__.py", line 62, in main_write
    tree_name=args.tree_name)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/write.py", line 27, in prepare_file_list
    full_list = expand_files.expand_file_list(files, prefix=prefix)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/catalogues/__init__.py", line 15, in expand_file_list
    return expand_file_list_generic(files, prefix, glob=glob)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/catalogues/__init__.py", line 46, in expand_file_list_generic
    expanded = glob(name)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/xrootd_glob.py", line 35, in glob
    return xrootd_glob(pathname)
  File "/home/tanm/miniconda3/envs/fast_lz/lib/python3.7/site-packages/fast_curator/xrootd_glob.py", line 57, in xrootd_glob
    for entry in dirlist["dirlist"]:
TypeError: 'NoneType' object is not subscriptable
``

**Comment by benkrikler** [comment]
I think this has been solved by moving to the official version of xrootd_glob which we added to the official xrootd python bindings.  That has better error checking and should prevent this issue arising.  Feel free to reopen this if we see it happen again though!
